try 
{
    let num=5
    let result=manoj+1
    console.log(result);
} catch (error) 
{
    console.log("Please check reference "+error.name + " "+error.message);
}


